"""Add benchmark URL.

Revision ID: 112055db4eff
Revises: 7fc773c5907d
Create Date: 2022-10-20 14:46:46.681963
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '112055db4eff'
down_revision = '7fc773c5907d'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('url', sa.Text(), nullable=True))
    op.execute("UPDATE benchmark SET url = concat('https://hub.docker.com/r/', docker_image)")
    op.alter_column('benchmark', 'url', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benchmark', 'url')
    # ### end Alembic commands ###
